services:
  coordinador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coordinador
    image: coordinador:v3
    ports:
      - 8090:8080
    networks:
      - red_ej2

networks:
  red_ej2:
    external: true