apiVersion: v1
kind: Service
metadata:
  name: service-coordinador
  namespace: default
spec:
  clusterIP: None  # Esto lo hace un servicio headless
  selector:
    app: coordinador
  ports:
  - name: http
    port: 8080
    targetPort: 8080
