# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/

apiVersion: v1
kind: Service
metadata:
  name: public-service-coordinador

# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec
spec:
  type: LoadBalancer
  selector:
    app: coordinador
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080